# Fast test configuration for quick experiments

simulation:
  grid_size: [50, 50]  # Smaller grid
  max_timesteps: 10000
  population_cap: 100  # Fewer agents
  initial_population: 20
  seed: 42

environment:
  food_spawn_rate: 0.02  # More food for stability
  food_energy_value: 10

agent:
  initial_energy: 100
  base_metabolic_cost: 1.0
  movement_cost: 0.1
  perception_range: 2
  reproduction_threshold: 150
  reproduction_cost: 80

brain:
  input_size: 52
  hidden_size: 32
  output_size: 6
  activation: relu

evolution:
  mutation_rate: 0.1
  mutation_std: 0.1

logging:
  log_interval: 100  # Log more frequently
  checkpoint_interval: 1000
  analysis_interval: 5000
  visualization_fps: 30
  save_dir: experiments/logs
